# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 15:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+?9?1?([7-9]|1)?\\d{9}$')])),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
