# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harshit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
