# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 15:40
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=11)),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from=models.CharField(max_length=100), unique=True)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'stations',
            },
        ),
    ]
