# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 04:13
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
            options={
                'db_table': 'suggestiontypes',
                'ordering': ('slug',),
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='SuggestionSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=60, populate_from='name', unique=True)),
                ('suggestion_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xyz_comp', to='suggestion.SuggestionCategory')),
            ],
            options={
                'db_table': 'suggestion_subtypes',
                'ordering': ('slug',),
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.DeleteModel(
            name='Suggestion_Category',
        ),
        migrations.DeleteModel(
            name='Suggestion_Sub_Category',
        ),
        migrations.AlterUniqueTogether(
            name='suggestionsubcategory',
            unique_together=set([('suggestion_category', 'id')]),
        ),
    ]
