# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 15:40
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=50), unique=True)),
            ],
            options={
                'db_table': 'complaint_types',
                'ordering': ('slug',),
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Complaint_Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=60, populate_from=models.CharField(max_length=60), unique=True)),
                ('complaint_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xyz_comp', to='complaints.Complaint_Category')),
            ],
            options={
                'db_table': 'complaint_sub_types',
            },
        ),
    ]
