# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complaint_Category',
            new_name='ComplaintCategory',
        ),
        migrations.RenameModel(
            old_name='Complaint_Sub_Category',
            new_name='ComplaintSubCategory',
        ),
    ]
